# Generated by Django 6.1.1 on 2026-09-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioSudene',
            fields=[
                ('codigo_ibge', models.CharField(help_text='Exemplo: 3143302 para Montes Claros', max_length=7, primary_key=True, serialize=False, verbose_name='Código IBGE (7 dígitos)')),
                ('municipio', models.CharField(db_index=True, max_length=150, verbose_name='Nome do Município')),
                ('uf', models.CharField(default='MG', max_length=2, verbose_name='Unidade Federativa')),
                ('codigo_sudene', models.CharField(default='1', max_length=10, verbose_name='Código SUDENE')),
                ('recorte', models.CharField(default='Área de atuação da SUDENE', max_length=150, verbose_name='Recorte Territorial Legal')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude (Sede/Centroide)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude (Sede/Centroide)')),
                ('area_ibge_km2', models.FloatField(blank=True, null=True, verbose_name='Área Oficial IBGE (km²)')),
                ('pct_cerrado', models.FloatField(default=0.0, verbose_name='Percentual Cerrado (%)')),
                ('pct_caatinga', models.FloatField(default=0.0, verbose_name='Percentual Caatinga (%)')),
            ],
            options={
                'verbose_name': 'Município SUDENE-MG',
                'verbose_name_plural': 'Municípios SUDENE-MG',
                'ordering': ['municipio'],
            },
        ),
        migrations.CreateModel(
            name='Amostra25Cidade',
            fields=[
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='amostra_info', serialize=False, to='ambiental.municipiosudene', verbose_name='Município Selecionado')),
                ('ordem_amostral', models.PositiveIntegerField(db_index=True, verbose_name='Ordem Amostral (1 a 25)')),
                ('cidade_polo', models.BooleanField(default=False, help_text='True para Montes Claros (Polo Sertão)', verbose_name='É Cidade Polo Regional?')),
                ('justificativa_amostral', models.TextField(verbose_name='Justificativa Técnica da Seleção Amostral')),
            ],
            options={
                'verbose_name': 'Amostra 25 Cidades (Norte de Minas)',
                'verbose_name_plural': 'Amostra 25 Cidades (Norte de Minas)',
                'ordering': ['ordem_amostral'],
            },
        ),
    ]
