# Generated by Django 6.1.1 on 2026-09-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaciaHidrografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Bacia (ex: Bacia do Rio Verde Grande)')),
                ('codigo_bacia', models.CharField(max_length=30, unique=True, verbose_name='Código Oficial da Bacia')),
            ],
            options={
                'verbose_name': 'Bacia Hidrográfica',
                'verbose_name_plural': 'Bacias Hidrográficas',
            },
        ),
        migrations.CreateModel(
            name='EstacaoClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estacao', models.CharField(max_length=20, unique=True, verbose_name='Código da Estação (ex: INMET A514)')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude_metros', models.FloatField(default=600.0, verbose_name='Altitude (metros)')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacoes_climaticas', to='ambiental.municipiosudene', verbose_name='Município Sede')),
            ],
            options={
                'verbose_name': 'Estação Climática',
                'verbose_name_plural': 'Estações Climáticas',
            },
        ),
        migrations.CreateModel(
            name='RegistroClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True, verbose_name='Data e Hora da Medição')),
                ('temperatura_celsius', models.FloatField(verbose_name='Temperatura (°C)')),
                ('umidade_relativa_pct', models.FloatField(verbose_name='Umidade Relativa (%)')),
                ('precipitacao_mm', models.FloatField(default=0.0, verbose_name='Precipitação (mm)')),
                ('radiacao_solar_w_m2', models.FloatField(default=0.0, verbose_name='Radiação Solar (W/m²)')),
                ('velocidade_vento_ms', models.FloatField(default=0.0, verbose_name='Velocidade do Vento (m/s)')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='clima_hidro.estacaoclimatica', verbose_name='Estação de Coleta')),
            ],
            options={
                'verbose_name': 'Registro Climático',
                'verbose_name_plural': 'Registros Climáticos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Vereda')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('status_conservacao', models.CharField(choices=[('Preservada', 'Preservada'), ('Recuperação', 'Em Recuperação'), ('Antropizada', 'Antropizada / Degradada')], default='Preservada', max_length=30, verbose_name='Status de Conservação')),
                ('vazao_media_ls', models.FloatField(default=15.0, verbose_name='Vazão Média (L/s)')),
                ('bacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veredas', to='clima_hidro.baciahidrografica', verbose_name='Bacia Hidrográfica')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veredas', to='ambiental.municipiosudene', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Vereda',
                'verbose_name_plural': 'Veredas',
            },
        ),
    ]
